# Generated by Django 3.1.7 on 2021-04-03 16:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numAccount', models.CharField(help_text='Счет', max_length=100)),
                ('ostatok', models.CharField(help_text='Остаток', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=100, null=True)),
                ('avatar', models.ImageField(blank=True, default='blankuser.jpg', null=True, upload_to='')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Felial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numFelial', models.CharField(help_text='Номер фелиала', max_length=100)),
                ('address', models.CharField(help_text='Адрес', max_length=100)),
                ('tel', models.CharField(blank=True, help_text='Телефон', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TypesCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameCard', models.CharField(help_text='Название карты', max_length=100)),
                ('price', models.CharField(help_text='Цена', max_length=100)),
                ('description', models.CharField(help_text='Описание', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SecurityUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passport_num', models.CharField(help_text='Номер паспорта', max_length=20)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.client')),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numCard', models.CharField(help_text='Номер карты', max_length=100)),
                ('dateFinish', models.CharField(help_text='Дата окончания', max_length=100)),
                ('password', models.CharField(help_text='Пароль', max_length=100)),
                ('bankAccount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.account', verbose_name='Счет')),
                ('typeCard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.typescard', verbose_name='Тип карты')),
                ('user', models.ForeignKey(default=' ', on_delete=django.db.models.deletion.CASCADE, to='catalog.client', verbose_name='Пользователь')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='felial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.felial', verbose_name='Фелиал'),
        ),
    ]
