# Generated by Django 3.1.7 on 2021-04-04 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20210404_0201'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='account',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='catalog.account', verbose_name='Счет'),
        ),
    ]
