# Generated by Django 3.1.7 on 2021-04-04 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_client_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='account',
        ),
        migrations.AddField(
            model_name='account',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='catalog.client', verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='card',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='catalog.client', verbose_name='Пользователь'),
        ),
    ]
