# Generated by Django 3.1.7 on 2021-04-04 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20210404_2148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='felial',
            name='tel',
        ),
        migrations.AddField(
            model_name='felial',
            name='phone',
            field=models.CharField(blank=True, help_text='Телефон', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='Sending',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(help_text='Адрес', max_length=100)),
                ('dateSending', models.DateField(blank=True, null=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.card', verbose_name='Карта')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.client', verbose_name='Отправитель')),
            ],
        ),
    ]
