# Generated by Django 3.1.7 on 2021-04-04 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20210404_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='sending',
            name='num_send',
            field=models.CharField(default='', help_text='номер отправления', max_length=100),
        ),
    ]
