# Generated by Django 3.1.7 on 2021-04-20 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_sending_num_send'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='image',
            field=models.ImageField(blank=True, default='Batman.jpg', null=True, upload_to=''),
        ),
    ]
