# Generated by Django 3.1.7 on 2021-04-24 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_typescard_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='typescard',
            name='cashback',
            field=models.CharField(default='5%', help_text='Cashback', max_length=10),
        ),
        migrations.AddField(
            model_name='typescard',
            name='ccy',
            field=models.CharField(default='BYN', help_text='Валюта', max_length=3),
        ),
        migrations.AddField(
            model_name='typescard',
            name='validity_period',
            field=models.CharField(default='3 года', help_text='Срокдействия', max_length=100),
        ),
    ]
