# Generated by Django 3.1.7 on 2021-04-30 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_auto_20210424_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='sending',
            name='status',
            field=models.CharField(default='В обработке', help_text='Статус', max_length=100),
        ),
    ]
