# Generated by Django 3.1.7 on 2021-04-30 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_sending_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='sending',
            name='checkbox',
            field=models.BooleanField(default=False),
        ),
    ]
