# Generated by Django 3.1.7 on 2021-05-09 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_auto_20210501_0302'),
    ]

    operations = [
        migrations.AddField(
            model_name='typescard',
            name='paysystem',
            field=models.CharField(blank=True, choices=[('v', 'Visa'), ('m', 'MasterCard'), ('b', 'Белкарт')], default='v', help_text='Платежная система', max_length=1),
        ),
        migrations.AlterField(
            model_name='sending',
            name='status',
            field=models.CharField(blank=True, choices=[('1', 'В обработке'), ('2', 'На эмбоссировании'), ('3', 'Готова')], default='1', help_text='Платежная система', max_length=1),
        ),
    ]
