# Generated by Django 3.1.7 on 2021-05-09 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_auto_20210509_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sending',
            name='status',
            field=models.CharField(blank=True, choices=[('1', 'В обработке'), ('2', 'На эмбоссировании'), ('3', 'Готова')], default='1', help_text='Статус', max_length=1),
        ),
    ]
