# Generated by Django 3.1.7 on 2021-05-09 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_auto_20210509_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sending',
            name='status',
            field=models.CharField(blank=True, choices=[('o', 'В обработке'), ('e', 'На эмбоссировании'), ('g', 'Готова')], default='o', help_text='Статус', max_length=1),
        ),
    ]
