# Generated by Django 3.1.7 on 2021-05-09 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_auto_20210509_1144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sending',
            name='dateSending',
        ),
    ]
