# Generated by Django 3.1.7 on 2021-05-09 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_remove_sending_datesending'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sending',
            name='checkbox',
            field=models.BooleanField(default=False, help_text='Отправить по адресу'),
        ),
    ]
