# Generated by Django 3.1.7 on 2021-05-09 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_auto_20210509_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sending',
            name='status',
            field=models.CharField(blank=True, choices=[('В обработке', 'В обработке'), ('На эмбоссировании', 'На эмбоссировании'), ('Готова', 'Готова')], default='В обработке', help_text='Статус', max_length=20),
        ),
    ]
