# Generated by Django 3.1.7 on 2021-05-11 15:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0022_auto_20210509_1528'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleSummary',
            fields=[
            ],
            options={
                'verbose_name': 'Sale Summary',
                'verbose_name_plural': 'Sales Summary',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('catalog.sending',),
        ),
        migrations.AddField(
            model_name='sending',
            name='dateOFF',
            field=models.CharField(default=datetime.datetime(2021, 5, 11, 18, 14, 44, 784303), help_text='Дата оформления', max_length=100),
        ),
    ]
