# Generated by Django 3.1.7 on 2021-05-12 03:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0023_auto_20210511_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sending',
            name='dateOFF',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
