# Generated by Django 3.1.7 on 2021-05-12 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0024_auto_20210512_0614'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salesummary',
            options={'verbose_name': 'Sending Summary', 'verbose_name_plural': 'Sendings Summary'},
        ),
    ]
