# Generated by Django 3.1.7 on 2021-05-12 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0025_auto_20210512_0623'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='typescard',
            name='paysystem',
        ),
    ]
