# Generated by Django 3.1.7 on 2021-05-12 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0027_typescard_paysystem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='typescard',
            name='paysystem',
        ),
    ]
