# Generated by Django 3.1.7 on 2021-05-13 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0028_remove_typescard_paysystem'),
    ]

    operations = [
        migrations.AddField(
            model_name='typescard',
            name='paysystem',
            field=models.CharField(blank=True, choices=[('v', 'Visa'), ('m', 'MasterCard'), ('b', 'Белкарт')], default='v', help_text='Платежная система', max_length=1),
        ),
    ]
