# Generated by Django 3.1.7 on 2021-05-13 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0029_typescard_paysystem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sending',
            name='dateOFF',
        ),
    ]
