# Generated by Django 3.1.7 on 2021-05-13 03:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0032_remove_sending_dateoff'),
    ]

    operations = [
        migrations.AddField(
            model_name='sending',
            name='dateOFF',
            field=models.DateField(default=datetime.date.today, help_text='Дата оформления'),
        ),
    ]
