# Generated by Django 3.1.7 on 2021-05-15 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0033_sending_dateoff'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salesummary',
            options={'verbose_name': 'Sending Summary', 'verbose_name_plural': 'Sending Summary'},
        ),
        migrations.AlterField(
            model_name='typescard',
            name='ccy',
            field=models.CharField(default='BYN', help_text='Валюта', max_length=20),
        ),
    ]
