# Generated by Django 3.1.7 on 2021-05-15 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0034_auto_20210515_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typescard',
            name='price',
            field=models.CharField(help_text='Цена', max_length=1000),
        ),
    ]
