# Generated by Django 3.1.7 on 2021-05-16 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0036_auto_20210516_0000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='password',
        ),
        migrations.AlterField(
            model_name='sending',
            name='num_send',
            field=models.CharField(blank=True, default='', help_text='номер отправления', max_length=100),
        ),
    ]
